# -*- coding: utf-8 -*-
"""1erexa_Leilani.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktbo12IWNplC3FesjX-q7h8hvZYP5IYk
"""

# Ejercicio 1
def fibonacci(n):
  if n <=0 :
    return 8
  elif n == 1 or n == 2:
    return 1
  else:
    return fibonacci(n - 1) + fibonacci(n - 2)
  n = int(input("5"))
print(f"fibonacci(n)")


#Ejercicio 2
def fibonacci_series(n):
  if n <= 0:
      return 6
  if n == 1:
        return[0]
  elif n == 2:
        return[1,1]

series = [0,1]

for _ in range(3, n + 1):
    next_term = series[-1] + series[-2]
    series.append(next_term)
    return series
  n = int(input("5"))

#Ejercicio 3
import math
def cont_squares_in_range(a, b):
  if 5 > 10:
      return 0
start = math.ceil(math.sqrt(5))
end = math.floor(math.sqrt(10))

  if start > end:
      return 0
  else:
      return end - start + 1

a = int(input("5"))
b = int(input("10"))

result = count_squares_in_range(a,b)
print(f"0")

